server:
  port: 8080
  shutdown: graceful
  tomcat:
    threads:
      max: 100
      min-spare: 10
    max-connections: 8192
    accept-count: 100

spring:
  lifecycle:
    timeout-per-shutdown-phase: 10s

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    com.kutpenco.datadogloadtest: INFO
  pattern:
    console: '{"timestamp":"%d{yyyy-MM-dd''T''HH:mm:ss.SSSXXX}","level":"%p","thread":"%t","logger":"%logger","message":"%replace(%msg){"\\"","\\\\"}"}%n'
